name: Publish Release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create a Release
        run: echo "$SONATYPE_USERNAME"