name: Publish Release
'on': workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OSSRH_USERNAME: '${{ secrets.OSSRH_USERNAME }}'
      OSSRH_PASSWORD: '${{ secrets.OSSRH_PASSWORD }}'
      SONATYPE_STAGING_PROFILE_ID: '${{ secrets.SONATYPE_STAGING_PROFILE_ID }}'
      SIGNING_KEY_ID: '${{ secrets.SIGNING_KEY_ID }}'
      SIGNING_PASSWORD: '${{ secrets.SIGNING_PASSWORD }}'
      SIGNING_SECRET_KEY_RING_FILE: '${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}'
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build VYou-Core
        run: './gradlew vyou-core:build'
      - name: Build VYou-UI
        run: './gradlew vyou-ui:build'
      - name: Publish both libraries to Maven Central
        run: './gradlew :vyou-core:publishReleasePublicationToSonatypeRepository :vyou-ui:publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository'